#!/usr/bin/env bash
# install.sh — set up the claude-box tool on this machine.
#
# What it does:
#   1. detects your home + git dir (override with flags/env)
#   2. ensures the host files the container mounts exist (creates empty stubs)
#   3. writes .env
#   4. builds the Docker image
#   5. wires `cclaude` into your ~/.bashrc
#
# Usage:
#   ./install.sh                         # auto-detect everything
#   ./install.sh --git-dir /c/Users/me/Documents/github
#   ./install.sh --home /c/Users/me
#   ./install.sh --no-build              # skip docker build
#   ./install.sh --no-bashrc             # don't touch ~/.bashrc
#   ./install.sh --force                 # overwrite an existing .env
#
# Works in Git Bash on Windows and in bash on Linux/macOS.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ---- options ---------------------------------------------------------------
GIT_DIR_RAW=""
CLAUDE_HOME_RAW="$HOME"
BOX_DIR_RAW="$HOME/.claude-box"
DO_BUILD=1
DO_BASHRC=1
FORCE=0
BASHRC_FILE="$HOME/.bashrc"

while [ "$#" -gt 0 ]; do
    case "$1" in
        --git-dir)     GIT_DIR_RAW="$2"; shift 2 ;;
        --home)        CLAUDE_HOME_RAW="$2"; shift 2 ;;
        --box-dir)     BOX_DIR_RAW="$2"; shift 2 ;;
        --bashrc)      BASHRC_FILE="$2"; shift 2 ;;
        --no-build)    DO_BUILD=0; shift ;;
        --no-bashrc)   DO_BASHRC=0; shift ;;
        --force)       FORCE=1; shift ;;
        -h|--help)     sed -n '2,30p' "$0"; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 1 ;;
    esac
done

# The git dir defaults to the parent of this repo (claude-box lives inside it).
[ -n "$GIT_DIR_RAW" ] || GIT_DIR_RAW="$(dirname "$SCRIPT_DIR")"

# ---- platform / path conversion -------------------------------------------
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*) IS_WIN=1 ;;
    *) IS_WIN=0 ;;
esac

# Convert a POSIX path to a Docker-bind-friendly form.
# On Windows: /c/Users/me -> C:/Users/me. Elsewhere: unchanged.
to_mount() {
    if [ "$IS_WIN" = 1 ]; then
        echo "$1" | sed -E 's#^/([A-Za-z])/#\U\1:/#'
    else
        echo "$1"
    fi
}

CLAUDE_HOME="$(to_mount "$CLAUDE_HOME_RAW")"
GIT_DIR="$(to_mount "$GIT_DIR_RAW")"
BOX_DIR="$(to_mount "$BOX_DIR_RAW")"

echo "==> claude-box install"
echo "    repo      : $SCRIPT_DIR"
echo "    home      : $CLAUDE_HOME   (host: $CLAUDE_HOME_RAW)"
echo "    git dir   : $GIT_DIR   (mounted at /workspace)"
echo "    box config: $BOX_DIR   (isolated Claude config)"
echo

# ---- 1. checks -------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
    echo "ERROR: docker not found. Install Docker Desktop / Docker Engine first." >&2
    exit 1
fi
if ! docker info >/dev/null 2>&1; then
    echo "WARNING: docker daemon not reachable. Start Docker, then re-run (or use --no-build)." >&2
fi
if [ ! -d "$GIT_DIR_RAW" ]; then
    echo "WARNING: git dir '$GIT_DIR_RAW' does not exist yet." >&2
fi

# ---- 2. ensure mounted host paths exist (so bind mounts don't fail) --------
echo "==> ensuring mounted host files exist under $CLAUDE_HOME_RAW"
mkdir -p "$CLAUDE_HOME_RAW/.ssh"
[ -f "$CLAUDE_HOME_RAW/.gitconfig" ]   || : > "$CLAUDE_HOME_RAW/.gitconfig"
[ -f "$CLAUDE_HOME_RAW/.bashrc" ]      || : > "$CLAUDE_HOME_RAW/.bashrc"

# ---- 3. write .env ---------------------------------------------------------
if [ -f .env ] && [ "$FORCE" -ne 1 ]; then
    echo "==> .env already exists (use --force to overwrite); leaving it."
else
    cat > .env <<EOF
# Generated by install.sh. Use FORWARD slashes even on Windows.
CLAUDE_HOME=$CLAUDE_HOME
GIT_DIR=$GIT_DIR
BOX_DIR=$BOX_DIR
CLAUDE_VERSION=latest

# Proxy is read from your host environment (HTTP_PROXY/HTTPS_PROXY/NO_PROXY) at
# run time. Uncomment here only to force a value that overrides the environment:
# HTTP_PROXY=http://proxy.corp.example:8080
# HTTPS_PROXY=http://proxy.corp.example:8080
# NO_PROXY=localhost,127.0.0.1,::1
EOF
    echo "==> wrote .env"
fi

# Upgrade path: an older .env may predate BOX_DIR — append it if missing.
if ! grep -qE '^BOX_DIR=' .env 2>/dev/null; then
    echo "BOX_DIR=$BOX_DIR" >> .env
    echo "==> added BOX_DIR to existing .env"
fi

# Report any proxy the container will inherit from this environment.
if [ -n "${HTTPS_PROXY:-${HTTP_PROXY:-${https_proxy:-${http_proxy:-}}}}" ]; then
    echo "==> proxy detected in environment: ${HTTPS_PROXY:-${HTTP_PROXY:-${https_proxy:-$http_proxy}}}"
fi

# ---- 3b. seed the isolated box config from your real ~/.claude -------------
if [ -d "$CLAUDE_HOME_RAW/.claude" ]; then
    bash "$SCRIPT_DIR/seed-config.sh" "$CLAUDE_HOME_RAW/.claude" \
        || echo "WARNING: seeding failed; re-run ./seed-config.sh later." >&2
else
    echo "==> no ~/.claude to seed from; the box will start with empty config."
    mkdir -p "$BOX_DIR_RAW/.claude"
    [ -f "$BOX_DIR_RAW/.claude.json" ] || echo '{}' > "$BOX_DIR_RAW/.claude.json"
fi

# ---- 4. build --------------------------------------------------------------
if [ "$DO_BUILD" -eq 1 ]; then
    if docker info >/dev/null 2>&1; then
        echo "==> building image (this can take a few minutes)…"
        docker compose build
    else
        echo "==> skipping build (docker daemon not running)."
    fi
else
    echo "==> skipping build (--no-build)."
fi

# ---- 5. wire ~/.bashrc -----------------------------------------------------
if [ "$DO_BASHRC" -eq 1 ]; then
    line="source \"$SCRIPT_DIR/bashrc-snippet.sh\""
    if [ -f "$BASHRC_FILE" ] && grep -qF "bashrc-snippet.sh" "$BASHRC_FILE"; then
        echo "==> $BASHRC_FILE already sources the snippet."
    else
        printf '\n######## Claude Docker (claude-box)\n%s\n' "$line" >> "$BASHRC_FILE"
        echo "==> added snippet source to $BASHRC_FILE"
    fi
else
    echo "==> skipping ~/.bashrc wiring (--no-bashrc)."
fi

echo
echo "==> done. Next:"
echo "    1) reload your shell:   source \"$BASHRC_FILE\""
echo "    2) log in once:         cclaudelogin"
echo "    3) use it:              cclaude   (then 'cd <repo>' and 'claude')"
